### ISSUE TITLE
Update to React-Admin v3

### ISSUE THREAD

**Issue by LaszloDev** [benwinding/react-admin-firebase#46]
React-Admin planning to release v3 this summer. Right now they are finalizing the alpha and started to preparing the migration guide.
Are there any plans to start migrating this package to work with v3? I did a quick check yesterday and there are some breaking changes that will be impacting this package.

https://github.com/marmelab/react-admin/releases

Next branch: https://github.com/marmelab/react-admin/blob/next/UPGRADE.md

**TODOs**
- [x] Removed RA realtime as per https://github.com/marmelab/react-admin/pull/3908#issue-334448261
- [x] Implemented authProvider as object instead of function
- [x] authProvider.login method will now check for auth state change if no email and password is provided - enabling easy usage with third party Oauth firebase login flows (simply use useLogin without username and password **OR** specify '/' as the redirect URL as the checkAuth method will take care of making sure the user is logged in when redirecting)
- [x] Added example for usage with https://github.com/firebase/firebaseui-web-react resolves https://github.com/benwinding/react-admin-firebase/issues/34
- [x] Make react, react-admin and react-dom peerDependencies
- [x] Update demo project

Thanks to @simonberger (https://github.com/benwinding/react-admin-firebase/pull/67)

- [ ] Update docs

**Beta Version** 

We are getting closer to the stable version of this package which supports `react-admin` v3. Thanks to @simonbuerger he provided a pull request (https://github.com/benwinding/react-admin-firebase/pull/67) with the needed work.

To try the beta version of the package use the following to manually update the package in your project (for npm use `npm install`):
- update `react-admin` to the lastest version
-  `npm install` / `yarn add github:benwinding/react-admin-firebase#upgrade-to-react-admin-v3`

**Comment by benwinding** [comment]
Hi @LaszloDev,

Yes sounds good, maybe we could version up the npm library to 3.0 to be inline with the `react-admin` versioning (and easier for users).

I'll keep this branch here for version 3 upgrades if anyone wants to contribute:

https://github.com/benwinding/react-admin-firebase/tree/upgrade-to-react-admin-v3

Cheers,
Ben

**Comment by LaszloDev** [comment]
Hey @benwinding,
thanks for providing a new branch. Could you create a GitHub project for it, so we can keep track of the tasks needed to be done for v3.0 as a milestone?

**Comment by benwinding** [comment]
Hey @LaszloDev,
Great idea, I've added a project to track the progress here: 

https://github.com/benwinding/react-admin-firebase/projects/1

The hardest thing to change is probably the AuthProvider. [They've removed actions](https://github.com/marmelab/react-admin/blob/next/UPGRADE.md#no-more-redux-actions-for-authentication), which our implementation relies on (USER_LOGIN, USER_LOGOUT, USER_CHECK), so we'll need to figure out a new way using hooks.

If anyone would like to start working on this with me, let me know!

Cheers,
Ben

**Comment by LaszloDev** [comment]
v3 migration:
`ra-realtime` has been removed - https://github.com/marmelab/react-admin/pull/3908#issue-334448261

Please add that to the project

**Comment by LaszloDev** [comment]
To check out the beta release with `react-admin` support in your local project:
`yarn add github:benwinding/react-admin-firebase#upgrade-to-react-admin-v3`

**Comment by LaszloDev** [comment]
@simonbuerger thanks again for your work.
I was not able to change the target branch for your pull request to the local `upgrade-to-react-admin-v3`, so I guess we have to create a new pull request so we can work together on finalizing it, as I would like to make some more changes, at least regards the readme before merging it to the `master`. Please check if you can change the target branch, otherwise I would close this pull request and open a new one.

**Comment by valentinalexeev** [comment]
Dear @LaszloDev, I have created my own AuthProvider for v3 that follows the new spec and also relies on FirebaseUI for the logic of providers/methods/etc...

See https://gist.github.com/valentinalexeev/594fb2e1268851c60a9252b777655a63

I can also create a pull request if you find it useful.

**Comment by RWOverdijk** [comment]
@benwinding Did you close this because it works now, or because... I don't know, other reasons.

**Comment by benwinding** [comment]
Hi @RWOverdijk ,

Sorry about the delay but the upgrade is finished and merged into master https://github.com/benwinding/react-admin-firebase/pull/67 (which automatically closed this issue)

It's deployed to npm under the major version `3.0.0` https://www.npmjs.com/package/react-admin-firebase/v/3.0.0 

Check it out and let me know if there's any issues,

Cheers,
Ben

**Comment by RWOverdijk** [comment]
Aye. I also see the default query stuff has been added. That's cool because I've spent the past year yelling at my screen. Nice work man :)
